balancigastos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('equipos/',include("equipos_y_vehiculos.urls")),
    path('contabilidad/',include("contabilidad.urls")),
    path('proyectos/',include("proyectos.urls")),
    path('empleados/',include("empleados.urls")),
    path('usuarios/',include("usuarios.urls")),
    path('presupuestos/',include("presupuestos.urls")),
    path('',include("clientes.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clientes/urls.py
from django.urls import path
from . import views
from .views import pagina_principal

app_name = 'clientes'

urlpatterns = [
    path("registrar-cliente",views.crear_cliente, name = "crear_cliente"),
    path("",pagina_principal, name="pagina_principal"),
]

contabilidad/urls.py
from django.urls import path
from . import views
from contabilidad.views import GastosVehiculosListView, GastosGeneralesListView, GastosMaterialesListView, GastosManoObraListView, GastosEquiposListView, IngresosListView, GastosSeguridadListView

app_name = 'contabilidad'

urlpatterns = [
    # Path de listas
    path("<slug:slug>/gastos-generales",GastosGeneralesListView.as_view(),name="gastos_generales"),
    path("<slug:slug>/gastos-vehiculos",GastosVehiculosListView.as_view(),name="gastos_vehiculos"),
    path("<slug:slug>/gastos-materiales",GastosMaterialesListView.as_view(),name="gastos_materiales"),
    path("<slug:slug>/gastos-equipos",GastosEquiposListView.as_view(),name="gastos_equipos"),
    path("<slug:slug>/gastos-seguridad",GastosSeguridadListView.as_view(),name="gastos_seguridad"),
    path("<slug:slug>/gastos-mano-obra",GastosManoObraListView.as_view(),name="gastos_mano_obra"),
    path("<slug:slug>/ingresos",IngresosListView.as_view(),name="ingresos"),
    
    # Path de registros
    path("registrar-gastos-generales/<slug:slug>",views.registro_gastos_generales, name="registro_gastos_generales"),
    path("registrar-gastos-vehiculos/<slug:slug>",views.registro_gastos_vehiculos, name="registro_gastos_vehiculos"),
    path("registrar-gastos-materiales/<slug:slug>",views.registro_gastos_materiales,name="registro_gastos_materiales"),
    path("registrar-gastos-equipos/<slug:slug>",views.registro_gastos_equipos,name="registro_gastos_equipos"),
    path("registrar-gastos-seguridad/<slug:slug>",views.registro_gastos_seguridad,name="registro_gastos_seguridad"),
    path("registrar-gastos-mano-obra/<slug:slug>",views.registro_gastos_mano_obra,name="registro_gastos_mano_obra"),
    path("registrar-ingreso/<slug:slug>",views.registro_ingresos,name="registro_ingresos"),

    # Path de ediciones
    path("editar-gastos-generales/<slug:slug>/<int:gasto_id>",views.registro_gastos_generales, name="editar_gastos_generales"),
    path("editar-gastos-vehiculos/<slug:slug>/<int:gasto_id>",views.registro_gastos_vehiculos, name="editar_gastos_vehiculos"),
    path("editar-gastos-materiales/<slug:slug>/<int:gasto_id>",views.registro_gastos_materiales,name="editar_gastos_materiales"),
    path("editar-gastos-equipos/<slug:slug>/<int:gasto_id>",views.registro_gastos_equipos,name="editar_gastos_equipos"),
    path("editar-gastos-seguridad/<slug:slug>/<int:gasto_id>",views.registro_gastos_seguridad,name="editar_gastos_seguridad"),
    path("editar-ingreso/<slug:slug>/<int:ingreso_id>",views.registro_ingresos,name="editar_ingresos"),

    # Path de eliminaciones
    path("eliminar-gastos-mano-obra/<slug:slug>/<int:gasto_id>",views.eliminar_gastos_mano_obra,name="eliminar_gastos_mano_obra"),
    path("eliminar-gastos-generales/<slug:slug>/<int:gasto_id>",views.eliminar_gastos_generales,name="eliminar_gastos_generales"),
    path("eliminar-gastos-vehiculos/<slug:slug>/<int:gasto_id>",views.eliminar_gastos_vehiculos,name="eliminar_gastos_vehiculos"),
    path("eliminar-gastos-materiales/<slug:slug>/<int:gasto_id>",views.eliminar_gastos_materiales,name="eliminar_gastos_materiales"),
    path("eliminar-gastos-equipos/<slug:slug>/<int:gasto_id>",views.eliminar_gastos_equipos,name="eliminar_gastos_equipos"),
    path("eliminar-gastos-seguridad/<slug:slug>/<int:gasto_id>",views.eliminar_gastos_seguridad,name="eliminar_gastos_seguridad"),
    path("eliminar-ingresos/<slug:slug>/<int:gasto_id>",views.eliminar_ingresos,name="eliminar_ingresos"),

    
]

empleados/urls.py
from django.urls import path
from . import views
from .views import EmpleadosListView, AsistenciasListView, NominasListView
app_name = 'empleados'

urlpatterns = [
    path("empleados/",EmpleadosListView.as_view(),name="empleados"),
    path("registro-empleado/",views.registro_empleados,name="registro_empleados"),
    path("asistencias/<slug:slug>",AsistenciasListView.as_view(),name="asistencias"),
    path("registro_asistencias/<slug:slug>",views.registro_asistencias,name="registro_asistencias"),
    path("registro_nominas/<slug:slug>",views.registro_nominas,name="registro_nominas"),
    path("nominas/<slug:slug>/<int:lote>",NominasListView.as_view(),name="nominas"),
    path("eliminar-empleado/<int:empleado_id>",views.eliminar_empleado,name="eliminar_empleado"),
    path("editar-empleado/<int:empleado_id>",views.editar_empleado,name="editar_empleado"),
    path("eliminar-asistencia/<slug:slug>/<int:asistencia_id>",views.eliminar_asistencia,name="eliminar_asistencia"),
]

proyectos/urls.py
from django.urls import path
from . import views
from proyectos.views import ProyectosListView, ProyectosDetailView, export_proyectos_to_excel, export_project_details_to_excel, actualizar_progreso


app_name = 'proyectos'

urlpatterns = [
    
    path("registrar-proyecto/",views.registrar_proyecto,name="registrar_proyecto"),
    path("editar-proyecto/<slug:slug>",views.registrar_proyecto,name="editar_proyecto"),
    path('eliminar_proyecto/<slug:slug>/', views.eliminar_proyecto, name='eliminar_proyecto'),
    path("",ProyectosListView.as_view(),name="proyectos"),
    path("proyectos/<slug:slug>/",ProyectosDetailView.as_view(),name="detalles_proyecto"),
    path('proyectos/<slug:slug>/toggle-estatus/', views.toggle_estatus_proyecto, name='toggle_estatus_proyecto'),
    path('exportar-proyectos/', export_proyectos_to_excel, name='export_proyectos_to_excel'),
    path('exportar-detalles-proyecto/<slug:proyecto_slug>/', export_project_details_to_excel, name='export_project_details_to_excel'),
    path("actualizar-progreso/<slug:slug>/",actualizar_progreso,name="actualizar_progreso"),

]

proyectos/forms.py
from django import forms
from .models import Proyectos
from django.core.exceptions import ValidationError

class ProyectosForm(forms.ModelForm):
    class Meta:
        model = Proyectos
        fields = ['proyecto','clave_proyecto','empresa','fecha_fin_estimada','presupuesto_estimado','ganancia_estimada']

        widgets = {
            'fecha_fin_estimada': forms.DateInput(attrs={'type': 'date', 'required': True}),
            'proyecto': forms.TextInput(attrs={'required': True}),
            'clave_proyecto': forms.TextInput(attrs={'required': True, 'pattern': '[A-Za-z0-9]+', 'title': 'Debe contener al menos una letra y solo letras o números.'}),
            'empresa': forms.TextInput(attrs={'required': True}),
            'presupuesto_estimado': forms.NumberInput(attrs={'required': True}),
            'ganancia_estimada': forms.NumberInput(attrs={'required': True}),
        }

proyectos/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.db.models import Sum
from django.db.models.functions import Coalesce
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView
from django.urls import reverse
from django.http import HttpResponse, JsonResponse

from .forms import ProyectosForm
from .models import Proyectos

from contabilidad.models import Ingresos, GastosGenerales, GastosVehiculos, GastosMateriales, GastosManoObra, GastosEquipos, GastosSeguridad
from empleados.models import Salario, Asistencias
from contabilidad.views import recalcular_totales_proyecto
from .graficas import grafica_ingresos_vs_gastos_semanales, grafica_ingresos_vs_gastos, grafica_gastos_categoria

from decimal import Decimal
from openpyxl import Workbook
import io

# Create your views here.

class ProyectosListView(LoginRequiredMixin,ListView):
    model = Proyectos
    template_name = "proyectos/proyectos.html"
    context_object_name = "projects"

    def get_queryset(self):
        # Obtener la queryset inicial
        queryset = Proyectos.objects.all()

        # Obtener los parámetros de filtro de la URL o de un formulario GET
        estatus = self.request.GET.get('estatus')
        empresa = self.request.GET.get('empresa')
        proyecto = self.request.GET.get('proyecto')
        total_min = self.request.GET.get('total_min')
        total_max = self.request.GET.get('total_max')

        # Aplicar los filtros si los valores no son nulos
        if estatus:
            queryset = queryset.filter(estatus=estatus)
        
        if empresa:
            queryset = queryset.filter(empresa__icontains=empresa)
        
        if proyecto:
            queryset = queryset.filter(proyecto__icontains=proyecto)
        
        if total_min:
            queryset = queryset.filter(total__gte=total_min)
        
        if total_max:
            queryset = queryset.filter(total__lte=total_max)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Calcular la suma del campo 'total' de todos los proyectos filtrados
        total_monto_neto = self.get_queryset().aggregate(total=Coalesce(Sum('total'),Decimal('0.00')))['total']
        
        # Pasar la suma total al contexto
        context['total_monto_neto'] = total_monto_neto
        
        # Pasar los filtros actuales para mantener el estado del formulario
        context['estatus'] = self.request.GET.get('estatus', '')
        context['empresa'] = self.request.GET.get('empresa', '')
        context['proyecto'] = self.request.GET.get('proyecto', '')
        context['total_min'] = self.request.GET.get('total_min', '')
        context['total_max'] = self.request.GET.get('total_max', '')

        # Generar la URL para eliminar proyecto y pasarlo al contexto
        eliminar_url = reverse('proyectos:eliminar_proyecto', kwargs={'slug': 'slug_placeholder'})
        context['eliminar_url_template'] = eliminar_url

        return context

    
class ProyectosDetailView(LoginRequiredMixin,DetailView):
    model = Proyectos
    template_name = "proyectos/proyectos_detalles.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        proyecto = self.get_object()

        # ----------------------------------------------------------------------#
        # Llamar a la función recalcular_totales_proyecto que está en views.py de contabilidad
        totales = recalcular_totales_proyecto(proyecto.id)
        # Añadir los valores recalculados al contexto
        context.update(totales)
        # ----------------------------------------------------------------------#

        # context['graph_json'] = grafica_ingresos_vs_gastos_semanales(proyecto.id)
        # context['graph_json2'] = grafica_ingresos_vs_gastos(proyecto.id)
        # context['graph_json3'] = grafica_gastos_categoria(proyecto.id)

        return context

@login_required
def registrar_proyecto(request, slug=None):
    if slug:
        # Si existe un slug, es un proyecto que se va a editar
        proyecto = get_object_or_404(Proyectos, slug=slug)
        registrar_proyectos_form = ProyectosForm(request.POST or None, instance=proyecto)
    else:
        # Si no existe slug, es un proyecto nuevo
        registrar_proyectos_form = ProyectosForm(request.POST or None)
    
    if request.method == "POST":
        if registrar_proyectos_form.is_valid():
            # Guardar el proyecto (nuevo o editado)
            proyecto = registrar_proyectos_form.save()
            # Redirigir a los detalles del proyecto después de guardar
            return redirect('proyectos:detalles_proyecto', slug=proyecto.slug)
    
    # Si el formulario no es válido o es un GET, mostrar el formulario
    return render(request, "proyectos/registrar_proyecto.html", {'proyectos_form': registrar_proyectos_form})

def eliminar_proyecto(request, slug):
    # Obtener el proyecto a través del slug
    proyecto = get_object_or_404(Proyectos, slug=slug)
    proyecto.delete()
    return redirect('proyectos:proyectos')

@login_required
def toggle_estatus_proyecto(request, slug):
    # Obtener el proyecto por su slug
    proyecto = get_object_or_404(Proyectos, slug=slug)

    # Alternar el estatus entre True (Activo) y False (Inactivo)
    proyecto.estatus = not proyecto.estatus
    proyecto.save()

    # Redirigir a la página de detalle del proyecto o a la lista de proyectos
    return redirect('proyectos:proyectos')

@login_required
def export_proyectos_to_excel(request):
    # Crea un libro de trabajo y una hoja
    wb = Workbook()
    ws = wb.active
    ws.title = 'Proyectos'

    # Añade encabezados
    headers = ['ID', 'Nombre', 'Empresa', 'Estatus', 'Resultados']  # Ajusta según tus campos
    ws.append(headers)

    # Añade datos de los proyectos
    proyectos = Proyectos.objects.all()  # Obtén todos los proyectos
    for proyecto in proyectos:
        ws.append([proyecto.id, proyecto.proyecto, proyecto.empresa, proyecto.estatus, proyecto.total])  # Ajusta según tus campos

    # Guarda el libro de trabajo en un buffer
    buffer = io.BytesIO()
    wb.save(buffer)
    buffer.seek(0)

    # Prepara la respuesta HTTP
    response = HttpResponse(buffer, content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = 'attachment; filename=proyectos.xlsx'
    return response


@login_required
def export_project_details_to_excel(request, proyecto_slug):
    # Obtén el proyecto
    proyecto = Proyectos.objects.get(slug=proyecto_slug)
    
    # Crea un libro de trabajo y varias hojas
    wb = Workbook()

    # Hoja de Proyectos
    ws1 = wb.active
    ws1.title = 'Proyectos'
    headers1 = ['ID', 'Proyecto', 'Empresa', 'Estatus', 'Total']
    ws1.append(headers1)
    ws1.append([proyecto.id, proyecto.proyecto, proyecto.empresa, proyecto.estatus, proyecto.total])

    # Hoja de Ingresos
    ws2 = wb.create_sheet(title='Ingresos')
    headers2 = ['ID', 'Concepto', 'Ingreso', 'IVA', 'Referencia', 'Fecha']
    ws2.append(headers2)
    ingresos = Ingresos.objects.filter(proyecto=proyecto)
    for ingreso in ingresos:
        fecha_ingreso = ingreso.fecha
        ws2.append([ingreso.id, ingreso.concepto, ingreso.monto, ingreso.iva, ingreso.referencia, fecha_ingreso])

    # Hoja de Gastos Vehículos
    ws3 = wb.create_sheet(title='Gastos Vehículos')
    headers3 = ['ID', 'Vehículo', 'Cantidad Combustible', 'Monto', 'IVA', 'Ubicación', 'Proveedor', 'Conductor', 'Fecha']
    ws3.append(headers3)
    gastos_vehiculos = GastosVehiculos.objects.filter(proyecto=proyecto)
    for gasto in gastos_vehiculos:
        fecha_gasto = gasto.fecha
        ws3.append([
            gasto.id,
            gasto.vehiculo.vehiculo,  # Extrae el nombre del vehículo
            gasto.cantidad_combustible,
            gasto.monto,
            gasto.iva,
            gasto.ubicacion,
            gasto.proveedor,
            gasto.conductor,
            fecha_gasto
        ])

    # Hoja de Gastos Generales
    ws4 = wb.create_sheet(title='Gastos Generales')
    headers4 = ['ID', 'Concepto', 'Comprador', 'Monto', 'IVA', 'Notas', 'Proveedor', 'Fecha']
    ws4.append(headers4)
    gastos_generales = GastosGenerales.objects.filter(proyecto=proyecto)
    for gasto in gastos_generales:
        fecha_gasto = gasto.fecha
        ws4.append([gasto.id, gasto.concepto, gasto.comprador, gasto.monto, gasto.iva, gasto.notas, gasto.proveedor, fecha_gasto])

    # Hoja de Gastos Materiales
    ws4 = wb.create_sheet(title='Gastos Materiales')
    headers4 = ['ID', 'Concepto', 'Comprador', 'Monto', 'IVA', 'Descripción', 'Proveedor', 'Fecha']
    ws4.append(headers4)
    gastos_materiales = GastosMateriales.objects.filter(proyecto=proyecto)
    for gasto in gastos_materiales:
        fecha_gasto_material = gasto.fecha
        ws4.append([gasto.id, gasto.concepto, gasto.comprador, gasto.monto, gasto.iva, gasto.descripcion, gasto.proveedor, fecha_gasto_material])

    # Hoja de Gastos Seguridad
    ws4 = wb.create_sheet(title='Gastos Seguridad')
    headers4 = ['ID', 'Concepto', 'Comprador', 'Monto', 'IVA', 'Descripción', 'Proveedor', 'Fecha']
    ws4.append(headers4)
    gastos_seguridad = GastosSeguridad.objects.filter(proyecto=proyecto)
    for gasto in gastos_seguridad:
        fecha_gasto_seguridad = gasto.fecha
        ws4.append([gasto.id, gasto.concepto, gasto.comprador, gasto.monto, gasto.iva, gasto.descripcion, gasto.proveedor, fecha_gasto_seguridad])

    # Hoja de Gastos Mano de obra
    ws4 = wb.create_sheet(title='Gastos Mano de Obra')
    headers4 = ['ID', 'Nómina', 'IMSS', 'INFONAVIT', 'ISN', 'ISR', 'Horas extras', 'Monto', 'Lote', 'Fecha']
    ws4.append(headers4)
    gastos_mano_obra = GastosManoObra.objects.filter(proyecto=proyecto)
    for gasto in gastos_mano_obra:

proyectos/templates/proyectos/proyectos_detalles.html
{% extends 'base.html' %}
{% block title %}Detalles de proyecto{% endblock %}
{% load currency %}
{% block content %}
{% load static %}
{% if object %}
<h4 class="h4 text-center mt-3 text-success">Detalles {{ object.proyecto }}</h4>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active" aria-current="page" href="{% url 'proyectos:detalles_proyecto' object.slug %}">Detalles
      de proyecto</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'contabilidad:gastos_vehiculos' object.slug %}">Gastos vehículos</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'contabilidad:gastos_generales' object.slug %}">Gastos generales</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'contabilidad:gastos_materiales' object.slug %}">Gastos materiales</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'contabilidad:gastos_mano_obra' object.slug %}">Gastos mano de obra</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'contabilidad:gastos_seguridad' object.slug %}">Gastos seguridad</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'contabilidad:gastos_equipos' object.slug %}">Gastos equipos</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'contabilidad:ingresos' object.slug %}">Ingresos</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'empleados:asistencias' object.slug %}">Asistencias</a>
  </li>
</ul>

<hr class="border border-success border-3 opacity-75">

<h4 class="h4 text-center mt-3 mb-3 text-success">Progreso</h4>

<div id="valor-progreso" style="display:none;" data-progreso="{{ object.progreso }}"></div>

<div class="progress" role="progressbar" aria-label="Default striped example" aria-valuenow="10" aria-valuemin="0"
  aria-valuemax="100" id="progress-bar-container">
  <div class="progress-bar progress-bar-striped" id="progress-bar">{{ object.progreso }}%</div>
</div>

<form class="d-flex flex-column" method="POST" action="{% url 'proyectos:actualizar_progreso' object.slug %}">
  {% csrf_token %}
  <label for="customRange1" class="form-label mt-3 fs-4 text-center text-success">Control de progreso</label>
  <input type="range" class="form-range" id="customRange1" name="progreso" min="0" max="100" step="1" value="{{ object.progreso }}">
  
  <div class="mt-3 d-flex justify-content-end">
    <button type="submit" id="actualizarProgreso" class="btn btn-primary">Actualizar progreso</button>
  </div>
</form>

<hr class="border border-success border-3 opacity-75">

<div class="row justify-content-evenly">
  <ul class="list-group col-4">
    <li class="list-group-item text-center"><strong>Ingresos</strong></li>
    <hr class="border border-success border-3 opacity-75">
    <li class="list-group-item list-group-item-primary"><strong>Ingresos Totales:</strong> {{ total_ingresos|pesos }}
    </li>
    <li class="list-group-item"><strong>Ingresos Totales IVA:</strong> {{ total_iva_ingresos|pesos }}</li>


    <a href="{% url 'proyectos:export_project_details_to_excel' object.slug %}" class="btn btn-success m-5">Descargar
      proyecto en Excel</a>

      <a href="{% url 'proyectos:editar_proyecto' object.slug %}" class="btn btn-success m-5">Editar detalles del proyecto</a>

  </ul>

  <ul class="list-group col-4">
    <li class="list-group-item text-center"><strong>Egresos</strong></li>
    <hr class="border border-success border-3 opacity-75">
    <li class="list-group-item list-group-item-primary"><strong>Gastos totales:</strong> {{ total_gastos|pesos }}</li>
    <li class="list-group-item"><strong>Gastos vehículos:</strong> {{ gastos_vehiculos|pesos }} </li>
    <li class="list-group-item"><strong>Gastos generales:</strong> {{ gastos_generales|pesos }} </li>
    <li class="list-group-item"><strong>Gastos materiales:</strong> {{ gastos_materiales|pesos }} </li>
    <li class="list-group-item"><strong>Gastos mano de obra:</strong> {{ gastos_mano_obra|pesos }}</li>
    <li class="list-group-item"><strong>Gastos seguridad:</strong> {{ gastos_seguridad|pesos }} </li>
    <li class="list-group-item"><strong>Gastos equipos:</strong> {{ gastos_equipos|pesos }} </li>
    <li class="list-group-item"><strong>Total I.V.A. gastos:</strong> {{ total_iva_gastos|pesos }}</li>
  </ul>

  <ul class="list-group col-4">
    <li class="list-group-item text-center"><strong>Resultados</strong></li>
    <hr class="border border-success border-3 opacity-75">
    <li class="list-group-item"><strong>Empresa:</strong> {{ object.empresa }}</li>
    <li class="list-group-item"><strong>Estatus:</strong>{% if object.estatus == True %} Activo {% else %} Inactivo
      {% endif %}</li>
    <li class="list-group-item"><strong>Nombre del proyecto:</strong> {{ object.proyecto }}</li>
    <li class="list-group-item"><strong>Clave de proyecto:</strong> {{ object.clave_proyecto }}</li>
    <li class="list-group-item"><strong>Fecha de inicio:</strong> {{ object.fecha_creacion }}</li>
    <li class="list-group-item"><strong>Fecha estimada de finalización:</strong> {{ object.fecha_fin_estimada }}</li>
    <li class="list-group-item"><strong>Presupuesto estimado:</strong> {{ object.presupuesto_estimado|pesos }}</li>
    <li class="list-group-item"><strong>Ganancia estimada:</strong> {{ object.ganancia_estimada|pesos }}</li>
    <li class="list-group-item list-group-item-primary"><strong>Resultado Neto:</strong> {{ total_neto|pesos }}</li>
    <li class="list-group-item"><strong>I.V.A. Neto:</strong> {{ iva_neto|pesos }}</li>
  </ul>

</div>


<hr class="border border-success border-3 opacity-75 mt-5">

<!-- <h4 class="h4 text-center mt-3 mb-3 text-success">Tablero de {{ object.proyecto }}</h4>

<div class="container mt-2">
  <div class="row">
    <div class="col-md-12">
      <div class="card mb-4">
        <div class="card-body">
          <h5 class="card-title">Ingresos vs Gastos - Semanales</h5>
          <div id="grafica1" style="width:100%;height:300px;"></div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="card mb-4">
        <div class="card-body">
          <h5 class="card-title">Porcentaje de gastos por categoría</h5>
          <div id="grafica3" style="width:100%;height:400px;"></div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card mb-4">
        <div class="card-body">
          <h5 class="card-title">Ingresos vs Gastos - Totales</h5>
          <div id="grafica2" style="width:100%;height:400px;"></div>
        </div>
      </div>
    </div>
  </div>
</div> -->

<script type="text/javascript" src="{% static 'js/barra_progreso.js' %}"></script>

<script type="text/javascript">
  document.addEventListener("DOMContentLoaded", function () {
    var progreso = document.getElementById('valor-progreso').getAttribute('data-progreso');
    console.log(progreso);
  actualizarBarraProgreso(progreso);  
  });

//  var graph = JSON.parse('{{ graph_json|escapejs }}');
//  var graph2 = JSON.parse('{{ graph_json2|escapejs }}');
//  var graph3 = JSON.parse('{{ graph_json3|escapejs }}');
//  Plotly.newPlot('grafica1', graph.data, graph.layout);
//  Plotly.newPlot('grafica2', graph2.data, graph2.layout);
//  Plotly.newPlot('grafica3', graph3.data, graph3.layout);
</script>

{% endif %}

{% endblock %}

proyectos/templates/proyectos/registrar_proyecto.html
{% extends 'base.html' %}
{% block title %}Registro de proyectos{% endblock %}

{% block content %}
{% load static %}

<h4 class="h4 text-center text-danger">Registrar proyecto</h4>

<hr class="border border-danger border-3 opacity-75">

<div class="container text-center">
    <form method="post">
        {% csrf_token %}

        {{proyectos_form}}

        <button type="submit" class="btn btn-danger">Registrar proyecto</button>
    </form>
</div>

<script type="text/javascript" src="{% static 'js/validacion_proyectos.js' %}"></script>

{% endblock %}