balancigastos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('equipos/',include("equipos_y_vehiculos.urls")),
    path('contabilidad/',include("contabilidad.urls")),
    path('proyectos/',include("proyectos.urls")),
    path('empleados/',include("empleados.urls")),
    path('usuarios/',include("usuarios.urls")),
    path('presupuestos/',include("presupuestos.urls")),
    path('',include("clientes.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clientes/urls.py
from django.urls import path
from . import views
from .views import pagina_principal

app_name = 'clientes'

urlpatterns = [
    path("registrar-cliente",views.crear_cliente, name = "crear_cliente"),
    path("",pagina_principal, name="pagina_principal"),
]

contabilidad/urls.py
from django.urls import path
from . import views
from contabilidad.views import GastosVehiculosListView, GastosGeneralesListView, GastosMaterialesListView, GastosManoObraListView, GastosEquiposListView, IngresosListView, GastosSeguridadListView

app_name = 'contabilidad'

urlpatterns = [
    # Path de listas
    path("<slug:slug>/gastos-generales",GastosGeneralesListView.as_view(),name="gastos_generales"),
    path("<slug:slug>/gastos-vehiculos",GastosVehiculosListView.as_view(),name="gastos_vehiculos"),
    path("<slug:slug>/gastos-materiales",GastosMaterialesListView.as_view(),name="gastos_materiales"),
    path("<slug:slug>/gastos-equipos",GastosEquiposListView.as_view(),name="gastos_equipos"),
    path("<slug:slug>/gastos-seguridad",GastosSeguridadListView.as_view(),name="gastos_seguridad"),
    path("<slug:slug>/gastos-mano-obra",GastosManoObraListView.as_view(),name="gastos_mano_obra"),
    path("<slug:slug>/ingresos",IngresosListView.as_view(),name="ingresos"),
    
    # Path de registros
    path("registrar-gastos-generales/<slug:slug>",views.registro_gastos_generales, name="registro_gastos_generales"),
    path("registrar-gastos-vehiculos/<slug:slug>",views.registro_gastos_vehiculos, name="registro_gastos_vehiculos"),
    path("registrar-gastos-materiales/<slug:slug>",views.registro_gastos_materiales,name="registro_gastos_materiales"),
    path("registrar-gastos-equipos/<slug:slug>",views.registro_gastos_equipos,name="registro_gastos_equipos"),
    path("registrar-gastos-seguridad/<slug:slug>",views.registro_gastos_seguridad,name="registro_gastos_seguridad"),
    path("registrar-gastos-mano-obra/<slug:slug>",views.registro_gastos_mano_obra,name="registro_gastos_mano_obra"),
    path("registrar-ingreso/<slug:slug>",views.registro_ingresos,name="registro_ingresos"),

    # Path de ediciones
    path("editar-gastos-generales/<slug:slug>/<int:gasto_id>",views.registro_gastos_generales, name="editar_gastos_generales"),
    path("editar-gastos-vehiculos/<slug:slug>/<int:gasto_id>",views.registro_gastos_vehiculos, name="editar_gastos_vehiculos"),
    path("editar-gastos-materiales/<slug:slug>/<int:gasto_id>",views.registro_gastos_materiales,name="editar_gastos_materiales"),
    path("editar-gastos-equipos/<slug:slug>/<int:gasto_id>",views.registro_gastos_equipos,name="editar_gastos_equipos"),
    path("editar-gastos-seguridad/<slug:slug>/<int:gasto_id>",views.registro_gastos_seguridad,name="editar_gastos_seguridad"),
    path("editar-ingreso/<slug:slug>/<int:ingreso_id>",views.registro_ingresos,name="editar_ingresos"),

    # Path de eliminaciones
    path("eliminar-gastos-mano-obra/<slug:slug>/<int:gasto_id>",views.eliminar_gastos_mano_obra,name="eliminar_gastos_mano_obra"),
    path("eliminar-gastos-generales/<slug:slug>/<int:gasto_id>",views.eliminar_gastos_generales,name="eliminar_gastos_generales"),
    path("eliminar-gastos-vehiculos/<slug:slug>/<int:gasto_id>",views.eliminar_gastos_vehiculos,name="eliminar_gastos_vehiculos"),
    path("eliminar-gastos-materiales/<slug:slug>/<int:gasto_id>",views.eliminar_gastos_materiales,name="eliminar_gastos_materiales"),
    path("eliminar-gastos-equipos/<slug:slug>/<int:gasto_id>",views.eliminar_gastos_equipos,name="eliminar_gastos_equipos"),
    path("eliminar-gastos-seguridad/<slug:slug>/<int:gasto_id>",views.eliminar_gastos_seguridad,name="eliminar_gastos_seguridad"),
    path("eliminar-ingresos/<slug:slug>/<int:gasto_id>",views.eliminar_ingresos,name="eliminar_ingresos"),

    
]

empleados/urls.py
from django.urls import path
from . import views
from .views import EmpleadosListView, AsistenciasListView, NominasListView
app_name = 'empleados'

urlpatterns = [
    path("empleados/",EmpleadosListView.as_view(),name="empleados"),
    path("registro-empleado/",views.registro_empleados,name="registro_empleados"),
    path("asistencias/<slug:slug>",AsistenciasListView.as_view(),name="asistencias"),
    path("registro_asistencias/<slug:slug>",views.registro_asistencias,name="registro_asistencias"),
    path("registro_nominas/<slug:slug>",views.registro_nominas,name="registro_nominas"),
    path("nominas/<slug:slug>/<int:lote>",NominasListView.as_view(),name="nominas"),
    path("eliminar-empleado/<int:empleado_id>",views.eliminar_empleado,name="eliminar_empleado"),
    path("editar-empleado/<int:empleado_id>",views.editar_empleado,name="editar_empleado"),
    path("eliminar-asistencia/<slug:slug>/<int:asistencia_id>",views.eliminar_asistencia,name="eliminar_asistencia"),
]

equipos_y_vehiculos/urls.py
from django.urls import path
from . import views

app_name = 'equipos_y_vehiculos'

urlpatterns = [
    path('equipos/',views.index,name='index'),
    path("registrar-vehiculo",views.registro_vehiculos, name="registro_vehiculos"),
]

proyectos/urls.py
from django.urls import path
from . import views
from proyectos.views import ProyectosListView, ProyectosDetailView, export_proyectos_to_excel, export_project_details_to_excel, actualizar_progreso


app_name = 'proyectos'

urlpatterns = [
    
    path("registrar-proyecto/",views.registrar_proyecto,name="registrar_proyecto"),
    path("editar-proyecto/<slug:slug>",views.registrar_proyecto,name="editar_proyecto"),
    path('eliminar_proyecto/<slug:slug>/', views.eliminar_proyecto, name='eliminar_proyecto'),
    path("",ProyectosListView.as_view(),name="proyectos"),
    path("proyectos/<slug:slug>/",ProyectosDetailView.as_view(),name="detalles_proyecto"),
    path('proyectos/<slug:slug>/toggle-estatus/', views.toggle_estatus_proyecto, name='toggle_estatus_proyecto'),
    path('exportar-proyectos/', export_proyectos_to_excel, name='export_proyectos_to_excel'),
    path('exportar-detalles-proyecto/<slug:proyecto_slug>/', export_project_details_to_excel, name='export_project_details_to_excel'),
    path("actualizar-progreso/<slug:slug>/",actualizar_progreso,name="actualizar_progreso"),

]

contabilidad/models.py
from django.db import models
from proyectos.models import Proyectos
from equipos_y_vehiculos.models import Vehiculos
from django.utils import timezone
from decimal import Decimal
from django.core.exceptions import ValidationError
# Create your models here.

class GastosVehiculos(models.Model):
    
    proyecto = models.ForeignKey(Proyectos, related_name= 'gastos_vehiculos',on_delete=models.CASCADE)
    vehiculo = models.ForeignKey(Vehiculos, related_name='vehiculos',on_delete=models.CASCADE)
    cantidad_combustible = models.FloatField()
    monto = models.DecimalField(max_digits=10, decimal_places=2,null=False,default=Decimal('0.00'))
    iva = models.DecimalField(max_digits=10, decimal_places=2,null=False,default=Decimal('0.00'))
    proveedor = models.CharField(max_length=100,null=False)
    ubicacion = models.CharField(max_length=100,null=False)
    conductor = models.CharField(max_length=100,null=False)
    fecha = models.DateField(default=timezone.now)

    def __str__(self):
        return f"{self.proyecto.proyecto} - {self.vehiculo}"
    
class GastosGenerales(models.Model):
    proyecto = models.ForeignKey(Proyectos, related_name= 'gastos_generales',on_delete=models.CASCADE)
    concepto = models.CharField(max_length=255,null=False)
    comprador = models.CharField(max_length=255,null=False)
    monto = models.DecimalField(max_digits=10, decimal_places=2,null=False,default=Decimal('0.00'))
    iva = models.DecimalField(max_digits=10, decimal_places=2,null=False,default=Decimal('0.00'))
    notas = models.TextField(blank=True)
    proveedor = models.CharField(max_length=100,null=False)
    fecha = models.DateField(default=timezone.now)

    def __str__(self):
        return f"{self.proyecto.proyecto} - {self.concepto}"
    
class GastosMateriales(models.Model):
    proyecto = models.ForeignKey(Proyectos, related_name= 'gastos_materiales',on_delete=models.CASCADE)
    concepto = models.CharField(max_length=255,null=False)
    comprador = models.CharField(max_length=255,null=False)
    monto = models.DecimalField(max_digits=10, decimal_places=2,null=False,default=Decimal('0.00'))
    iva = models.DecimalField(max_digits=10, decimal_places=2,null=False,default=Decimal('0.00'))
    descripcion = models.TextField(blank=True)
    proveedor = models.CharField(max_length=100,null=False)
    fecha = models.DateField(default=timezone.now)

    def __str__(self):
        return f"{self.proyecto.proyecto} - {self.concepto}"
    
class GastosSeguridad(models.Model):
    proyecto = models.ForeignKey(Proyectos, related_name= 'gastos_seguridad',on_delete=models.CASCADE)
    concepto = models.CharField(max_length=255,null=False)
    comprador = models.CharField(max_length=255,null=False)
    monto = models.DecimalField(max_digits=10, decimal_places=2,null=False,default=Decimal('0.00'))
    iva = models.DecimalField(max_digits=10, decimal_places=2,null=False,default=Decimal('0.00'))
    descripcion = models.TextField(blank=True)
    proveedor = models.CharField(max_length=100,null=False)
    fecha = models.DateField(default=timezone.now)

    def __str__(self):
        return f"{self.proyecto.proyecto} - {self.concepto}"
    
class GastosManoObra(models.Model):
    proyecto = models.ForeignKey(Proyectos, related_name= 'gastos_mano_obra',on_delete=models.CASCADE)
    nomina = models.DecimalField(max_digits=10, decimal_places=2,null=False,default=Decimal('0.00'))
    imss = models.DecimalField(max_digits=10, decimal_places=2,null=False,default=Decimal('0.00'))
    infonavit = models.DecimalField(max_digits=10, decimal_places=2,null=False,default=Decimal('0.00'))
    isn = models.DecimalField(max_digits=10, decimal_places=2,null=False,default=Decimal('0.00'))
    isr = models.DecimalField(max_digits=10, decimal_places=2,null=False,default=Decimal('0.00'))
    horas_extras = models.DecimalField(max_digits=10, decimal_places=2,null=False, default=Decimal('0.00'))
    monto = models.DecimalField(max_digits=10, decimal_places=2,default=Decimal('0.00'))
    lote = models.IntegerField(unique=True)
    fecha = models.DateField(default=timezone.now)

    def __str__(self):
        return f"{self.proyecto.proyecto}"
    
class GastosEquipos(models.Model):

    TIEMPO_RENTA = [
        ('RENTA_MENSUAL','renta mensual'),
        ('RENTA_SEMANAL','renta semanal'),
        ('RENTA_DIARIA','renta diaria'),
        ('PROPIEDAD','Propiedad')
    ]

    proyecto = models.ForeignKey(Proyectos, related_name= 'gastos_equipos',on_delete=models.CASCADE)
    concepto = models.CharField(max_length=255,null=False)
    comprador = models.CharField(max_length=255,null=False)
    tiempo_renta = models.CharField(max_length=100,choices=TIEMPO_RENTA,default='RENTA_MENSUAL')
    monto = models.DecimalField(max_digits=10, decimal_places=2,null=False,default=Decimal('0.00'))
    iva = models.DecimalField(max_digits=10, decimal_places=2,null=False,default=Decimal('0.00'))
    descripcion = models.TextField(blank=True)
    proveedor = models.CharField(max_length=100,null=False)
    fecha = models.DateField(default=timezone.now)

    def __str__(self):
        return f"{self.proyecto.proyecto} - {self.concepto}"
    
class Ingresos(models.Model):

    proyecto = models.ForeignKey(Proyectos,related_name='ingresos',on_delete=models.CASCADE)
    concepto = models.CharField(max_length=255,null=False)
    monto = models.DecimalField(max_digits=10, decimal_places=2,null=False,default=Decimal('0.00'))
    iva = models.DecimalField(max_digits=10, decimal_places=2,null=False,default=Decimal('0.00'))
    referencia = models.CharField(max_length=100,null=False)
    fecha = models.DateField(default=timezone.now,null=False)

    def __str__(self):
        return self.proyecto.proyecto

contabilidad/forms.py
from django import forms
from .models import GastosVehiculos, GastosGenerales, GastosEquipos, GastosSeguridad, GastosManoObra, GastosMateriales, Ingresos
from django.utils import timezone
from django.core.exceptions import ValidationError

 # Obtén la hora actual en la zona horaria local
now = timezone.now().date()

class GastosVehiculosForm(forms.ModelForm):
    class Meta:
        model = GastosVehiculos
        fields = ['vehiculo','cantidad_combustible','monto','ubicacion', 'proveedor','conductor','fecha']
        widgets = {
            'fecha': forms.DateInput(attrs={'type': 'date'}),  # Calendar widget for 'fecha'
        }

    def clean_fecha(self):
        fecha = self.cleaned_data.get('fecha')

        # Check if the date is in the future
        if fecha > now:
            raise ValidationError('No puedes registrar un gasto con una fecha futura.')

        return fecha 

class GastosGeneralesForm(forms.ModelForm):
    class Meta:
        model = GastosGenerales
        fields = ['concepto','comprador','monto','notas','proveedor','fecha']
        widgets = {
            'fecha': forms.DateInput(attrs={'type': 'date'}),  # Calendar widget for 'fecha'
        }
    
    def clean_fecha(self):
        fecha = self.cleaned_data.get('fecha')

        # Check if the date is in the future
        if fecha > now:
            raise ValidationError('No puedes registrar un gasto con una fecha futura.')

        return fecha
    
class GastosMaterialesForm(forms.ModelForm):
    class Meta:
        model = GastosMateriales
        fields = ['concepto','comprador','monto','descripcion','proveedor','fecha']
        widgets = {
            'fecha': forms.DateInput(attrs={'type': 'date'}),  # Calendar widget for 'fecha'
        }

    def clean_fecha(self):
        fecha = self.cleaned_data.get('fecha')

        # Check if the date is in the future
        if fecha > now:
            raise ValidationError('No puedes registrar un gasto con una fecha futura.')

        return fecha 
    
class GastosManoObraForm(forms.ModelForm):
    class Meta:
        model = GastosManoObra
        fields = ['nomina','imss','infonavit','isn','isr','fecha']
        widgets = {
            'fecha': forms.DateInput(attrs={'type': 'date'}),  # Calendar widget for 'fecha'
        }

    def clean_fecha(self):
        fecha = self.cleaned_data.get('fecha')

        # Check if the date is in the future
        if fecha > now:
            raise ValidationError('No puedes registrar un gasto con una fecha futura.')

        return fecha 
    
class GastosEquiposForm(forms.ModelForm):
    class Meta:
        model = GastosEquipos
        fields = ['concepto','comprador','tiempo_renta','monto','descripcion', 'proveedor','fecha']
        widgets = {
            'fecha': forms.DateInput(attrs={'type': 'date'}),  # Calendar widget for 'fecha'
        }

    def clean_fecha(self):
        fecha = self.cleaned_data.get('fecha')

        # Check if the date is in the future
        if fecha > now:
            raise ValidationError('No puedes registrar un gasto con una fecha futura.')

        return fecha

class GastosSeguridadForm(forms.ModelForm):
    class Meta:
        model = GastosSeguridad
        fields = ['concepto','comprador','monto','descripcion', 'proveedor','fecha']
        widgets = {
            'fecha': forms.DateInput(attrs={'type': 'date'}),  # Calendar widget for 'fecha'
        }

    def clean_fecha(self):
        fecha = self.cleaned_data.get('fecha')

        # Check if the date is in the future
        if fecha > now:
            raise ValidationError('No puedes registrar un gasto con una fecha futura.')

        return fecha 
    
class IngresosForm(forms.ModelForm):
    class Meta:
        model = Ingresos
        fields = ['concepto','monto','referencia','fecha']

        widgets = {
            'fecha': forms.DateInput(attrs={'type': 'date'}),  # Calendar widget for 'fecha'
        }

    def clean_fecha(self):
        fecha = self.cleaned_data.get('fecha')

        # Check if the date is in the future
        if fecha > now:
            raise ValidationError('No puedes registrar un gasto con una fecha futura.')

        return fecha

contabilidad/templates/contabilidad/gastos_equipos_list.html
{% extends 'base.html' %}
{% block title %}Lista de gastos equipos{% endblock %}
{% load currency %}
{% block content %}

<h4 class="h4 text-center mt-3 text-danger"> Gastos equipos {{proyecto.proyecto}}</h4>

<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'proyectos:detalles_proyecto' proyecto.slug %}">Detalles de proyecto</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_vehiculos' proyecto.slug %}">Gastos
            vehículos</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_generales' proyecto.slug %}">Gastos generales</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_materiales' proyecto.slug %}">Gastos materiales</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_mano_obra' proyecto.slug %}">Gastos mano de obra</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_seguridad' proyecto.slug %}">Gastos seguridad</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'contabilidad:gastos_equipos' proyecto.slug %}">Gastos equipos</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:ingresos' proyecto.slug %}">Ingresos</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'empleados:asistencias' proyecto.slug %}">Asistencias</a>
    </li>
</ul>

<hr class="border border-danger border-3 opacity-75">

<div class="table-responsive">
    <table class="table table-stripped">
    
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Concepto</th>
                <th scope="col">Comprador</th>
                <th scope="col">Proveedor</th>
                <th scope="col">Tiempo de renta</th>
                <th scope="col">Monto</th>
                <th scope="col">I.V.A.</th>
                <th scope="col">Fecha</th>
            </tr>
        </thead>
        <tbody>
            {% for gasto in gastosequipos_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ gasto.concepto }}</td>
                <td>{{ gasto.comprador }}</td>
                <td>{{ gasto.proveedor }}</td>
                <td>{{ gasto.tiempo_renta }}</td>
                <td>{{ gasto.monto|pesos }}</td>
                <td>{{ gasto.iva|pesos }}</td>
                <td>{{ gasto.fecha|date:"d-M-y" }}</td>
                <td><a href="{% url 'contabilidad:editar_gastos_equipos' proyecto.slug gasto.id %}" class="btn btn-outline-danger">Editar</a></td>
                <td><a href="{% url 'contabilidad:eliminar_gastos_equipos' proyecto.slug gasto.id %}" onclick="return confirm('¿Estás seguro de que quieres eliminar este gasto?');" class="btn btn-outline-danger">Eliminar</a></td>
            </tr>
            {% endfor %}
            <tr>
                <td colspan="4"></td>
                <td><strong>Total:</strong></td>
                <td><strong>{{ total_monto|pesos }}</strong></td>
                <td><strong>{{ total_iva|pesos }}</strong></td>
            </tr>
        </tbody>
    </table>
</div>

<a class="btn btn-danger" href="{% url 'contabilidad:registro_gastos_equipos' proyecto.slug %}">Registrar gastos equipos</a>

{% endblock %}

contabilidad/templates/contabilidad/gastos_vehiculos_list.html
{% extends 'base.html' %}
{% block title %}Lista de gastos vehículos{% endblock %}
{% load currency %}
{% block content %}

<h4 class="h4 text-center mt-3 text-danger"> Gastos de vehículos {{proyecto.proyecto}}</h4>

<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'proyectos:detalles_proyecto' proyecto.slug %}">Detalles de proyecto</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'contabilidad:gastos_vehiculos' proyecto.slug %}">Gastos vehículos</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_generales' proyecto.slug %}">Gastos generales</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_materiales' proyecto.slug %}">Gastos materiales</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_mano_obra' proyecto.slug %}">Gastos mano de obra</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_seguridad' proyecto.slug %}">Gastos seguridad</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_equipos' proyecto.slug %}">Gastos equipos</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:ingresos' proyecto.slug %}">Ingresos</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'empleados:asistencias' proyecto.slug %}">Asistencias</a>
    </li>
</ul>

<hr class="border border-danger border-3 opacity-75">

<div class="table-responsive">

    <table class="table table-stripped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Vehiculo</th>
                <th scope="col">Placas</th>
                <th scope="col">Volumen de combustible (L)</th>
                <th scope="col">Monto</th>
                <th scope="col">I.V.A.</th>
                <th scope="col">Fecha</th>
            </tr>
        </thead>
        <tbody>
            {% for gasto in gastosvehiculos_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ gasto.vehiculo }}</td>
                <td>{{ gasto.vehiculo.placas }}</td>
                <td>{{ gasto.cantidad_combustible|floatformat:2 }}</td>
                <td>{{ gasto.monto|pesos }}</td>
                <td>{{ gasto.iva|pesos }}</td>
                <td>{{ gasto.fecha|date:"d-M-y" }}</td>
                <td><a href="{% url 'contabilidad:editar_gastos_vehiculos' proyecto.slug gasto.id %}" class="btn btn-outline-danger">Editar</a></td>
                <td><a href="{% url 'contabilidad:eliminar_gastos_vehiculos' proyecto.slug gasto.id %}" onclick="return confirm('¿Estás seguro de que quieres eliminar este gasto?');" class="btn btn-outline-danger">Eliminar</a></td>
            </tr>
            {% endfor %}
            <tr>
                <td colspan="3"></td>
                <td><strong>Total:</strong></td>
                <td><strong>{{ total_monto|pesos }}</strong></td>
                <td><strong>{{ total_iva|pesos }}</strong></td>
            </tr>
        </tbody>
    </table>
</div>

<div class="container m-4">
    <a href="{% url 'contabilidad:registro_gastos_vehiculos' proyecto.slug %}" class="btn btn-danger">Registrar gasto de vehículo</a>
    
    <a href="{% url 'equipos_y_vehiculos:registro_vehiculos' %}" class="btn btn-danger">Registrar vehículo</a>
</div>

{% endblock %}