balancigastos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('equipos/',include("equipos_y_vehiculos.urls")),
    path('contabilidad/',include("contabilidad.urls")),
    path('proyectos/',include("proyectos.urls")),
    path('empleados/',include("empleados.urls")),
    path('usuarios/',include("usuarios.urls")),
    path('presupuestos/',include("presupuestos.urls")),
    path('',include("clientes.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clientes/urls.py
from django.urls import path
from . import views
from .views import pagina_principal

app_name = 'clientes'

urlpatterns = [
    path("registrar-cliente",views.crear_cliente, name = "crear_cliente"),
    path("",pagina_principal, name="pagina_principal"),
]

contabilidad/urls.py
from django.urls import path
from . import views
from contabilidad.views import GastosVehiculosListView, GastosGeneralesListView, GastosMaterialesListView, GastosManoObraListView, GastosEquiposListView, IngresosListView, GastosSeguridadListView

app_name = 'contabilidad'

urlpatterns = [
    # Path de listas
    path("<slug:slug>/gastos-generales",GastosGeneralesListView.as_view(),name="gastos_generales"),
    path("<slug:slug>/gastos-vehiculos",GastosVehiculosListView.as_view(),name="gastos_vehiculos"),
    path("<slug:slug>/gastos-materiales",GastosMaterialesListView.as_view(),name="gastos_materiales"),
    path("<slug:slug>/gastos-equipos",GastosEquiposListView.as_view(),name="gastos_equipos"),
    path("<slug:slug>/gastos-seguridad",GastosSeguridadListView.as_view(),name="gastos_seguridad"),
    path("<slug:slug>/gastos-mano-obra",GastosManoObraListView.as_view(),name="gastos_mano_obra"),
    path("<slug:slug>/ingresos",IngresosListView.as_view(),name="ingresos"),
    
    # Path de registros
    path("registrar-gastos-generales/<slug:slug>",views.registro_gastos_generales, name="registro_gastos_generales"),
    path("registrar-gastos-vehiculos/<slug:slug>",views.registro_gastos_vehiculos, name="registro_gastos_vehiculos"),
    path("registrar-gastos-materiales/<slug:slug>",views.registro_gastos_materiales,name="registro_gastos_materiales"),
    path("registrar-gastos-equipos/<slug:slug>",views.registro_gastos_equipos,name="registro_gastos_equipos"),
    path("registrar-gastos-seguridad/<slug:slug>",views.registro_gastos_seguridad,name="registro_gastos_seguridad"),
    path("registrar-gastos-mano-obra/<slug:slug>",views.registro_gastos_mano_obra,name="registro_gastos_mano_obra"),
    path("registrar-ingreso/<slug:slug>",views.registro_ingresos,name="registro_ingresos"),

    # Path de ediciones
    path("editar-gastos-generales/<slug:slug>/<int:gasto_id>",views.registro_gastos_generales, name="editar_gastos_generales"),
    path("editar-gastos-vehiculos/<slug:slug>/<int:gasto_id>",views.registro_gastos_vehiculos, name="editar_gastos_vehiculos"),
    path("editar-gastos-materiales/<slug:slug>/<int:gasto_id>",views.registro_gastos_materiales,name="editar_gastos_materiales"),
    path("editar-gastos-equipos/<slug:slug>/<int:gasto_id>",views.registro_gastos_equipos,name="editar_gastos_equipos"),
    path("editar-gastos-seguridad/<slug:slug>/<int:gasto_id>",views.registro_gastos_seguridad,name="editar_gastos_seguridad"),
    path("editar-ingreso/<slug:slug>/<int:ingreso_id>",views.registro_ingresos,name="editar_ingresos"),

    # Path de eliminaciones
    path("eliminar-gastos-mano-obra/<slug:slug>/<int:gasto_id>",views.eliminar_gastos_mano_obra,name="eliminar_gastos_mano_obra"),
    path("eliminar-gastos-generales/<slug:slug>/<int:gasto_id>",views.eliminar_gastos_generales,name="eliminar_gastos_generales"),
    path("eliminar-gastos-vehiculos/<slug:slug>/<int:gasto_id>",views.eliminar_gastos_vehiculos,name="eliminar_gastos_vehiculos"),
    path("eliminar-gastos-materiales/<slug:slug>/<int:gasto_id>",views.eliminar_gastos_materiales,name="eliminar_gastos_materiales"),
    path("eliminar-gastos-equipos/<slug:slug>/<int:gasto_id>",views.eliminar_gastos_equipos,name="eliminar_gastos_equipos"),
    path("eliminar-gastos-seguridad/<slug:slug>/<int:gasto_id>",views.eliminar_gastos_seguridad,name="eliminar_gastos_seguridad"),
    path("eliminar-ingresos/<slug:slug>/<int:gasto_id>",views.eliminar_ingresos,name="eliminar_ingresos"),

    
]

empleados/urls.py
from django.urls import path
from . import views
from .views import EmpleadosListView, AsistenciasListView, NominasListView
app_name = 'empleados'

urlpatterns = [
    path("empleados/",EmpleadosListView.as_view(),name="empleados"),
    path("registro-empleado/",views.registro_empleados,name="registro_empleados"),
    path("asistencias/<slug:slug>",AsistenciasListView.as_view(),name="asistencias"),
    path("registro_asistencias/<slug:slug>",views.registro_asistencias,name="registro_asistencias"),
    path("registro_nominas/<slug:slug>",views.registro_nominas,name="registro_nominas"),
    path("nominas/<slug:slug>/<int:lote>",NominasListView.as_view(),name="nominas"),
    path("eliminar-empleado/<int:empleado_id>",views.eliminar_empleado,name="eliminar_empleado"),
    path("editar-empleado/<int:empleado_id>",views.editar_empleado,name="editar_empleado"),
    path("eliminar-asistencia/<slug:slug>/<int:asistencia_id>",views.eliminar_asistencia,name="eliminar_asistencia"),
]

proyectos/urls.py
from django.urls import path
from . import views
from proyectos.views import ProyectosListView, ProyectosDetailView, export_proyectos_to_excel, export_project_details_to_excel, actualizar_progreso


app_name = 'proyectos'

urlpatterns = [
    
    path("registrar-proyecto/",views.registrar_proyecto,name="registrar_proyecto"),
    path("editar-proyecto/<slug:slug>",views.registrar_proyecto,name="editar_proyecto"),
    path('eliminar_proyecto/<slug:slug>/', views.eliminar_proyecto, name='eliminar_proyecto'),
    path("",ProyectosListView.as_view(),name="proyectos"),
    path("proyectos/<slug:slug>/",ProyectosDetailView.as_view(),name="detalles_proyecto"),
    path('proyectos/<slug:slug>/toggle-estatus/', views.toggle_estatus_proyecto, name='toggle_estatus_proyecto'),
    path('exportar-proyectos/', export_proyectos_to_excel, name='export_proyectos_to_excel'),
    path('exportar-detalles-proyecto/<slug:proyecto_slug>/', export_project_details_to_excel, name='export_project_details_to_excel'),
    path("actualizar-progreso/<slug:slug>/",actualizar_progreso,name="actualizar_progreso"),

]

empleados/forms.py
from django import forms
from .models import Empleados

class EmpleadosForm(forms.ModelForm):
    class Meta:
        model = Empleados
        fields = ['nombres','apellido_paterno','apellido_materno','rfc','infonavit','imss']

class AsistenciaExcelForm(forms.Form):
    archivo_excel = forms.FileField()

class NominasExcelForm(forms.Form):
    archivo_excel = forms.FileField()

empleados/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Empleados, Asistencias, Salario, Lote
from proyectos.models import Proyectos
from contabilidad.models import GastosManoObra
from .forms import EmpleadosForm, AsistenciaExcelForm, NominasExcelForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from datetime import datetime, date
from django.db.models import Q
from decimal import Decimal, InvalidOperation
from django.db.models import Sum, F
from django.db.models.functions import Coalesce
from django.contrib import messages

import openpyxl

import re

# Create your views here.

### -------------------------------------------------------------------------- ###
### ------------------------Funciones auxiliares------------------------------ ###
### -------------------------------------------------------------------------- ###

# Función auxiliar para convertir la fecha del formato Excel a datetime
def convertir_fecha(fecha_excel):
    if isinstance(fecha_excel, date):
        return fecha_excel
    elif isinstance(fecha_excel, datetime):
        return fecha_excel.date()
    elif isinstance(fecha_excel, str):
        try:
            return datetime.strptime(fecha_excel, '%Y-%m-%d').date()
        except ValueError:
            print(f"Error: formato de fecha no válido en cadena: {fecha_excel}")
            return None
    elif isinstance(fecha_excel, (int, float)):
        try:
            return datetime.fromordinal(datetime(1900, 1, 1).toordinal() + int(fecha_excel) - 2).date()
        except Exception as e:
            print(f"Error: no se pudo convertir fecha numérica: {fecha_excel}. Error: {e}")
            return None
    else:
        print(f"Error: formato de fecha no reconocido: {fecha_excel}")
        return None

### -----------Función auxiliar para registrar los gastos de nómina----------- ###

def registro_gastos_mano_obra(proyecto,lote):

    ### Se calculan los valores que se van a pasar al modelo GastosManoObra ###
    nominas_result = Salario.objects.filter(lote=lote,proyecto=proyecto).aggregate(
        total_nominas=Coalesce(Sum('salario'),Decimal('0.00'))
    )
    nominas=nominas_result['total_nominas']
    infonavit_result = Salario.objects.filter(lote=lote,proyecto=proyecto).aggregate(
        total_infonavit=Coalesce(Sum('infonavit'),Decimal('0.00'))
    )
    infonavit=infonavit_result['total_infonavit']
    imss_result = Salario.objects.filter(lote=lote,proyecto=proyecto).aggregate(
        total_imss=Coalesce(Sum('imss'),Decimal('0.00'))
    )
    imss=imss_result['total_imss']
    isr_result = Salario.objects.filter(lote=lote,proyecto=proyecto).aggregate(
        total_isr=Coalesce(Sum('isr'),Decimal('0.00'))
    )
    isr=isr_result['total_isr']
    horas_extras_result = Salario.objects.filter(lote=lote,proyecto=proyecto).aggregate(
        total_horas_extras=Coalesce(Sum('horas_extras'),Decimal('0.00'))
    )
    horas_extras=horas_extras_result['total_horas_extras']
    
    isn = Decimal('0.03') * nominas
    total_monto = nominas + infonavit + imss + isr + horas_extras + isn

    ### -------------------------------------------------------------------------- ###

    # Crea una instancia en GastosManoObra
    GastosManoObra.objects.create(
        proyecto=proyecto,
        nomina=nominas,
        infonavit=infonavit,
        imss=imss,
        isn=isn,
        isr=isr,
        horas_extras=horas_extras,
        monto=total_monto,
        lote=lote
    )

    # Refleja en el estado general el gasto
    Proyectos.objects.filter(id=proyecto.id).update(
                    total=F('total') - total_monto,
                )
    ### -------------------------------Fin de la función ------------------------- ###
    ### -------------------------------------------------------------------------- ###
    ### -------------------------------------------------------------------------- ###

### -------------------------------------------------------------------------- ###
### ----------------------- Vistas de empleados ------------------------------ ###
### -------------------------------------------------------------------------- ###

class NominasListView(LoginRequiredMixin,ListView):
    model = Salario
    template_name = "empleados/nominas_list.html"
    context_object_name = "nominas"

    def get_queryset(self):
        slug = self.kwargs.get('slug')
        lote_id = self.kwargs.get('lote')
        proyecto = Proyectos.objects.get(slug=slug)
        lote = Lote.objects.get(id=lote_id)
        return Salario.objects.filter(proyecto=proyecto,lote=lote.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug = self.kwargs.get('slug')
        proyecto = Proyectos.objects.get(slug=slug)
        context['lote'] = self.kwargs.get('lote')
        context['proyecto'] = proyecto
        return context 

class AsistenciasListView(LoginRequiredMixin,ListView):
    model = Asistencias
    template_name = "empleados/asistencias.html"
    context_object_name = "asistencias"

    def get_queryset(self):
        slug = self.kwargs.get('slug')
        proyecto = Proyectos.objects.get(slug=slug)
        return Asistencias.objects.filter(proyecto=proyecto)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug = self.kwargs.get('slug')
        proyecto = Proyectos.objects.get(slug=slug)

        context['proyecto'] = proyecto
        return context 

class EmpleadosListView(LoginRequiredMixin,ListView):
    model = Empleados
    template_name = "empleados/empleados.html"
    context_object_name = "empleados"

    def get_queryset(self):
        # Obtener la queryset inicial
        queryset = Empleados.objects.all()

        # Obtener los parámetros de filtro de la URL o de un formulario GET
        empleado = self.request.GET.get('empleado')
        rfc = self.request.GET.get('rfc')
        imss = self.request.GET.get('imss')
        infonavit = self.request.GET.get('infonavit')

        # Aplicar los filtros si los valores no son nulos
        if empleado:
            queryset = queryset.filter(empleado=empleado)
        
        if rfc:
            queryset = queryset.filter(rfc__icontains=rfc)
        
        if imss:
            queryset = queryset.filter(imss__icontains=imss)

        if infonavit:
            queryset = queryset.filter(infonavit__icontains=infonavit)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Obtener el slug del proyecto desde la URL
        # slug = self.kwargs.get('slug')
        # Si necesitas obtener el proyecto con base en el slug:
        # proyecto = Proyectos.objects.get(slug=slug)

        # Pasar los filtros actuales para mantener el estado del formulario
        context['empleado'] = self.request.GET.get('empleado', '')
        context['rfc'] = self.request.GET.get('rfc', '')
        context['imss'] = self.request.GET.get('imss', '')
        context['infonavit'] = self.request.GET.get('infonavit', '')
        # context['project'] = proyecto

        return context

### -------------------------------------------------------------------------- ###
### ---------------------- Funciones de registro ----------------------------- ###
### -------------------------------------------------------------------------- ###

@login_required
def registro_empleados(request):

    empleados = Empleados.objects.all()

    if request.method == "POST":
        empleados_form = EmpleadosForm(request.POST)

        if empleados_form.is_valid():
            empleados_form.save()
            return redirect('empleados:empleados')
    else:
        empleados_form = EmpleadosForm()

    return render(request,'empleados/registrar_empleados.html',{'empleados_form':empleados_form,'empleados':empleados})

@login_required
def registro_asistencias(request,slug):
    proyecto = Proyectos.objects.get(slug=slug)
    if request.method == 'POST':
        form = AsistenciaExcelForm(request.POST, request.FILES)
        if form.is_valid():
            archivo_excel = request.FILES['archivo_excel']
            workbook = openpyxl.load_workbook(archivo_excel)

            # Cargar las dos hojas: "Asistencias" y "Horas Extras"
            hoja_asistencias = workbook['Asistencias']
            hoja_horas_extras = workbook['Horas Extras']

            # Extraer el proyecto desde la celda A1 de la hoja de asistencias
            clave_proyecto_hoja_asistencias = hoja_asistencias['B1'].value
            print(f"Proyecto ID: {clave_proyecto_hoja_asistencias}")  # Depuración
            # Obtenemos el proyecto del slug de la url
            proyecto = Proyectos.objects.get(slug=slug)
            clave_proyecto = proyecto.clave_proyecto
            print(f"Proyecto ID: {clave_proyecto}")  # Depuración
            
            # Esto es para validar que el proyecto de la hoja de asistencias coincida con el de la plataforma
            if not clave_proyecto_hoja_asistencias == clave_proyecto:
                messages.error(request, f'El proyecto de la hoja no coincide con el de la aplicación')
                return redirect('empleados:registro_asistencias',slug=slug)

            try:
                proyecto = Proyectos.objects.get(clave_proyecto=clave_proyecto, estatus=True)
                print(f"Proyecto encontrado: {proyecto.proyecto}")  # Depuración
            except Proyectos.DoesNotExist:
                print("El proyecto no existe o no está activo.")  # Depuración
                messages.error(request, f'El proyecto no existe o no está activo')
                return redirect('empleados:registro_asistencias',slug=slug)

            
            # Diccionario para almacenar los datos de asistencias y horas extras
            diccionario_asistencias = {

empleados/templates/empleados/asistencias.html
{% extends 'base.html' %}
{% block title %}Asistencias{% endblock %}
{% block content %}

<h4 class="h4 text-center text-danger mt-3">Asistencias {{ proyecto.proyecto }}</h4>

<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'proyectos:detalles_proyecto' proyecto.slug %}">Detalles de proyecto</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_vehiculos' proyecto.slug %}">Gastos
            vehículos</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_generales' proyecto.slug %}">Gastos generales</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_materiales' proyecto.slug %}">Gastos materiales</a>
    </li>
    <li class="nav-item">
        <a class="nav-link"
            href="{% url 'contabilidad:gastos_mano_obra' proyecto.slug %}">Gastos mano de obra</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_seguridad' proyecto.slug %}">Gastos seguridad</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_equipos' proyecto.slug %}">Gastos equipos</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:ingresos' proyecto.slug %}">Ingresos</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'empleados:asistencias' proyecto.slug %}">Asistencias</a>
    </li>
</ul>

<hr class="border border-danger border-3 opacity-75">


<div class="table-responsive">
   <table class="table table-striped">
      <thead>
         <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre completo</th>
            <th scope="col">RFC</th>
            <th scope="col">Fecha</th>
            <th scope="col">Asistencia</th>
            <th scope="col">Horas extras</th>
         </tr>
      </thead>
      {% if asistencias %}
      <tbody>
         {% for asistencia in asistencias %}
         <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ asistencia.empleado.nombres }} {{ asistencia.empleado.apellido_paterno }} {{ asistencia.empleado.apellido_materno }}</td>
            <td>{{ asistencia.empleado.rfc }}</td>
            <td>{{ asistencia.fecha }}</td>
            <td>{{ asistencia.asistencias }}</td>
            <td>{{ asistencia.horas_extras }}</td>
            <td><a href="{% url 'empleados:eliminar_asistencia' proyecto.slug asistencia.id %}" onclick="return confirm('¿Estás seguro de que quieres eliminar esta asistencia?');" class="btn btn-outline-danger">Eliminar</a></td>
         </tr>
         {% endfor %}
      </tbody>
      {% endif %}
   </table>
</div>

<a class="btn btn-danger mb-5" href="{% url 'empleados:registro_asistencias' proyecto.slug %}">Registrar asistencias</a>

{% endblock %}

empleados/templates/empleados/nominas_list.html
{% extends 'base.html' %}
{% block title %}Nóminas{% endblock %}
{% load currency %}
{% block content %}


<h4 class="h4 text-center text-danger mt-3">Nóminas {{ proyecto }}</h4>

<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'proyectos:detalles_proyecto' proyecto.slug %}">Detalles de proyecto</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_vehiculos' proyecto.slug %}">Gastos
            vehículos</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_generales' proyecto.slug %}">Gastos generales</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_materiales' proyecto.slug %}">Gastos materiales</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" aria-current="page"
            href="{% url 'contabilidad:gastos_mano_obra' proyecto.slug %}">Gastos mano de obra</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_seguridad' proyecto.slug %}">Gastos seguridad</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_equipos' proyecto.slug %}">Gastos equipos</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:ingresos' proyecto.slug %}">Ingresos</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'empleados:asistencias' proyecto.slug %}">Asistencias</a>
    </li>
</ul>

<hr class="border border-danger border-3 opacity-75">

{% if nominas %}
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">RFC</th>
                <th scope="col">Nombre</th>
                <th scope="col">Nómina</th>
                <th scope="col">INFONAVIT</th>
                <th scope="col">IMSS</th>
                <th scope="col">ISR</th>
                <th scope="col">Horas extras</th>
                <th scope="col">Lote</th>
            </tr>
        </thead>
        <tbody>
            {% for nomina in nominas %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ nomina.empleado.rfc }}</td>
                <td>{{ nomina.empleado.nombres }} {{ nomina.empleado.apellido_paterno }}
                    {{ nomina.empleado.apellido_materno }}</td>
                <td>{{ nomina.salario|pesos }}</td>
                <td>{{ nomina.infonavit|pesos }}</td>
                <td>{{ nomina.imss|pesos }}</td>
                <td>{{ nomina.isr|pesos }}</td>
                <td>{{ nomina.horas_extras|pesos }}</td>
                <td>{{ nomina.lote}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}

{% endblock %}

empleados/templates/empleados/registrar_asistencias.html
{% extends 'base.html' %}
{% block title %}Registro de asistencias{% endblock %}

{% block content %}

<h4 class="h4 text-center text-danger mt-3">Registro asistencias {{ proyecto.proyecto }}</h4>

<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'proyectos:detalles_proyecto' proyecto.slug %}">Detalles de proyecto</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_vehiculos' proyecto.slug %}">Gastos
            vehículos</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_generales' proyecto.slug %}">Gastos generales</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_materiales' proyecto.slug %}">Gastos materiales</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_mano_obra' proyecto.slug %}">Gastos mano de obra</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_seguridad' proyecto.slug %}">Gastos seguridad</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_equipos' proyecto.slug %}">Gastos equipos</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:ingresos' proyecto.slug %}">Ingresos</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" aria-current="page"
            href="{% url 'empleados:asistencias' proyecto.slug %}">Asistencias</a>
    </li>
</ul>

<hr class="border border-danger border-3 opacity-75">

<div class="container">
    <form method="post" enctype="multipart/form-data">
        <h4 class="h4 text-center text-danger">Registrar asistencias</h4>
        {% csrf_token %}
        {{ asistencias_form.as_p }}
        <button type="submit" class="btn btn-danger">Cargar asistencias</button>
        {% load static %}
        <a href="{% static 'documents/asistencias_template.xlsx' %}" class="btn btn-outline-danger">Descargar
            plantilla</a>
    </form>
</div>


{% endblock %}

empleados/templates/empleados/registrar_empleados.html
{% extends 'base.html' %}
{% block title %}Registro de empleados{% endblock %}

{% block content %}

<hr class="border border-danger border-3 opacity-75">

<div class="container">
    <form method="post">
        <h4 class="h4 text-center text-danger">Registrar empleado</h4>
        {% csrf_token %}
        {{ empleados_form.as_p }}
        <button type="submit" class="btn btn-danger">Registrar empleado</button>
    </form>
</div>

{% endblock %}

empleados/templates/empleados/registro_nominas.html
{% extends 'base.html' %}
{% block title %}Registro de nóminas{% endblock %}

{% block content %}

<h4 class="h4 text-center text-danger mt-3">Registro nóminas {{ proyecto.proyecto }}</h4>

<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'proyectos:detalles_proyecto' proyecto.slug %}">Detalles de proyecto</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_vehiculos' proyecto.slug %}">Gastos
            vehículos</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_generales' proyecto.slug %}">Gastos generales</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_materiales' proyecto.slug %}">Gastos materiales</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" aria-current="page"
            href="{% url 'contabilidad:gastos_mano_obra' proyecto.slug %}">Gastos mano de obra</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_seguridad' proyecto.slug %}">Gastos seguridad</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:gastos_equipos' proyecto.slug %}">Gastos equipos</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contabilidad:ingresos' proyecto.slug %}">Ingresos</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'empleados:asistencias' proyecto.slug %}">Asistencias</a>
    </li>
</ul>

<hr class="border border-danger border-3 opacity-75">

<div class="container">
    <form method="post" enctype="multipart/form-data">
        <h4 class="h4 text-center text-danger">Registrar nóminas</h4>
        {% csrf_token %}
        {{ nominas_form.as_p }}
        <button type="submit" class="btn btn-danger">Cargar nóminas</button>
        {% load static %}
        <a href="{% static 'documents/nominas_template.xlsx' %}" class="btn btn-outline-danger">Descargar
            plantilla</a>
    </form>
</div>



{% endblock %}