balancigastos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('equipos/',include("equipos_y_vehiculos.urls")),
    path('contabilidad/',include("contabilidad.urls")),
    path('proyectos/',include("proyectos.urls")),
    path('empleados/',include("empleados.urls")),
    path('usuarios/',include("usuarios.urls")),
    path('presupuestos/',include("presupuestos.urls")),
    path('',include("clientes.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clientes/urls.py
from django.urls import path
from . import views
from .views import pagina_principal

app_name = 'clientes'

urlpatterns = [
    path("registrar-cliente",views.crear_cliente, name = "crear_cliente"),
    path("",pagina_principal, name="pagina_principal"),
]

empleados/urls.py
from django.urls import path
from . import views
from .views import EmpleadosListView, AsistenciasListView, NominasListView
app_name = 'empleados'

urlpatterns = [
    path("empleados/",EmpleadosListView.as_view(),name="empleados"),
    path("registro-empleado/",views.registro_empleados,name="registro_empleados"),
    path("asistencias/<slug:slug>",AsistenciasListView.as_view(),name="asistencias"),
    path("registro_asistencias/<slug:slug>",views.registro_asistencias,name="registro_asistencias"),
    path("registro_nominas/<slug:slug>",views.registro_nominas,name="registro_nominas"),
    path("nominas/<slug:slug>/<int:lote>",NominasListView.as_view(),name="nominas"),
    path("eliminar-empleado/<int:empleado_id>",views.eliminar_empleado,name="eliminar_empleado"),
    path("editar-empleado/<int:empleado_id>",views.editar_empleado,name="editar_empleado"),
    path("eliminar-asistencia/<slug:slug>/<int:asistencia_id>",views.eliminar_asistencia,name="eliminar_asistencia"),
]

presupuestos/urls.py
from django.urls import path
from . import views

app_name = 'presupuestos'

urlpatterns = [
    path("presupuesto/",views.ingresar_datos_generales_presupuesto,name="ingresar_datos_cabecera_presupuesto"),
    path("presupuesto/<slug:slug>/precios-unitarios/",views.ingresar_precios_unitarios,name="ingresar_precios_unitarios"),
    path("presupuesto/<slug:slug>/ajuste-presupuesto/",views.ajuste_presupuesto,name="ajuste_presupuesto"),
    path("",views.lista_presupuestos,name="presupuestos"),
    path("confirmar-presupuesto/<slug:slug>",views.confirmar_presupuesto,name="confirmar_presupuesto"),
    path("presupuesto/vista-presupuesto/<slug:slug>/<int:version>",views.presupuesto,name="presupuesto"),
    path("presupuesto/generar-pdf-vista/<slug:slug>/<int:version>",views.generar_pdf_vista,name="generar_pdf"),
]

proyectos/urls.py
from django.urls import path
from . import views
from proyectos.views import ProyectosListView, ProyectosDetailView, export_proyectos_to_excel, export_project_details_to_excel, actualizar_progreso


app_name = 'proyectos'

urlpatterns = [
    
    path("registrar-proyecto/",views.registrar_proyecto,name="registrar_proyecto"),
    path("editar-proyecto/<slug:slug>",views.registrar_proyecto,name="editar_proyecto"),
    path('eliminar_proyecto/<slug:slug>/', views.eliminar_proyecto, name='eliminar_proyecto'),
    path("",ProyectosListView.as_view(),name="proyectos"),
    path("proyectos/<slug:slug>/",ProyectosDetailView.as_view(),name="detalles_proyecto"),
    path('proyectos/<slug:slug>/toggle-estatus/', views.toggle_estatus_proyecto, name='toggle_estatus_proyecto'),
    path('exportar-proyectos/', export_proyectos_to_excel, name='export_proyectos_to_excel'),
    path('exportar-detalles-proyecto/<slug:proyecto_slug>/', export_project_details_to_excel, name='export_project_details_to_excel'),
    path("actualizar-progreso/<slug:slug>/",actualizar_progreso,name="actualizar_progreso"),

]

usuarios/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = 'usuarios'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('', auth_views.LoginView.as_view(template_name='usuarios/login.html',), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='usuarios/password_change.html',success_url=reverse_lazy('usuarios:password_change_done')), name='password_change'),    
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='usuarios/password_change_done.html'), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='usuarios/password_reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='usuarios/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='usuarios/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='usuarios/password_reset_complete.html'), name='password_reset_complete'),
    path('profile/', views.profile, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} My site {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>

<body>
    {% if user.is_authenticated %}
    {% include 'navbar_profile.html' %}
    {% else %}
    {% include 'navbar.html' %}
    {% endif %}
    <div class="container">
        {% block content %}{% endblock %}
        {% if messages %}
        <div class="toast-container position-fixed bottom-0 end-0 p-3" style="z-index: 11;">
            {% for message in messages %}
            <div class="toast align-items-center text-bg-{{ message.tags }} border-0" role="alert" aria-live="assertive"
                aria-atomic="true" data-bs-delay="3000">
                <div class="d-flex">
                    <div class="toast-body">
                        {{ message }}
                    </div>
                    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"
                        aria-label="Close"></button>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var toastElList = [].slice.call(document.querySelectorAll('.toast'));
            var toastList = toastElList.map(function (toastEl) {
                return new bootstrap.Toast(toastEl);
            });
            toastList.forEach(toast => toast.show());
        });
    </script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

templates/error.html
{% extends 'base.html' %}
{% block title %}Error{% endblock %}

{% block content %}

{% include 'navbar_profile.html' %}

<h4 class="h4 text-center text-danger mt-3">Error</h4>

<strong>{{ mensaje }}</strong>


{% endblock %}

templates/navbar.html
{% load static %}
<div class="container-fluid bg-success-subtle">
  <nav class="navbar navbar-expand-lg">
    <div class="container">
      <a class="navbar-brand" href="{% url 'clientes:pagina_principal' %}">
        <img class="logo" src="{% static 'images/balancigastos.png' %}" alt="Logo">
      </a>
    </div>
  </nav>
</div>

templates/navbar_profile.html
{% load static %}
<div class="container-fluid bg-success-subtle">
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href="{% url 'proyectos:proyectos' %}">
                <img class="logo" src="{% static 'images/balancigastos.png' %}" alt="Logo">
            </a>
        </div>
        <div class="container">
            <ul class="nav nav-tabs justify-content-end fw-semibold">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Perfil
                    </a>
                    <ul class="dropdown-menu bg-success-subtle">
                        <li>
                            <a class="dropdown-item text-dark fw-semibold" href="{% url 'usuarios:profile' %}">Mi perfil</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item text-dark fw-semibold" href="{% url 'usuarios:password_change' %}">Cambiar contraseña</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item text-dark fw-semibold" href="{% url 'usuarios:edit_profile' %}">Editar perfil</a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'proyectos:proyectos' %}">Proyectos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'presupuestos:presupuestos' %}">Presupuestos</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Empleados
                    </a>
                    <ul class="dropdown-menu bg-success-subtle">
                        <li>
                            <a class="dropdown-item text-dark fw-semibold" href="{% url 'empleados:empleados' %}">Empleados</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item text-dark fw-semibold" href="{% url 'empleados:registro_empleados' %}">Registrar empleado</a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-danger" href="{% url 'usuarios:logout' %}">Cerrar sesión</a>
                </li>
            </ul>
        </div>
    </nav>
    <p class="text-capitalize text-dark fs-4 pb-3"><strong>| Bienvenido, {{ profile_username }}</strong></p>
</div>